### ISSUE TITLE
tslint support for the ts plugin?

### ISSUE THREAD

**Issue by johnnyreilly** [namics/webpack-config-plugins#1]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The ts plugin does not support tslint; the underlying [`fork-ts-checker-webpack-plugin`](https://github.com/Realytics/fork-ts-checker-webpack-plugin) supports this so it would be nice to use it.

## Expected behavior

If there is a `tslint.json` file in the root of the directory structure; then tslint functionality is switched on. 

## What is the motivation / use case for changing the behavior?

tslint is useful!

**Comment by janbiasi** [comment]
I'll clarify this question with the team and give you feedback asap!

cc @jantimon

**Comment by janbiasi** [comment]
We won't integrate TSLint directly into the `ts-config-webpack-plugin` as mostly the linting process should be generally separated from the build process, thus we suggest to create separate linting implementations run as pre-hook.
