### ISSUE TITLE
defaultRules

### ISSUE THREAD

**Issue by degiorgioo** [namics/webpack-config-plugins#41]
Would it be possible to use `defaultRules` instead of rules?

**Comment by degiorgioo** [comment]
Hi @jantimon as far I can see within the module documentation of webpack, the option for 'defaultRules' is not documented yet. [webpack | modules]( https://webpack.js.org/configuration/module/)

There is also an issue defined from the 21st May 2018:
https://github.com/webpack/webpack.js.org/issues/2176 

We should wait with investigating time in that. What's your opinion @jantimon ?

**Comment by janbiasi** [comment]
There's still no update from webpack regarding this issue/doc request so I guess we'll need to wait a little bit longer for this one.

**Comment by ernscht** [comment]
closing, as there are no changes in sight.
