### ISSUE TITLE
Upgrade scss-config-webpack-plugin dependencies

### ISSUE THREAD

**Issue by jantimon** [namics/webpack-config-plugins#44]
The scss-config-webpack-plugin dependencies are out of date.

Unfortunately upgrading them causes test failures.

**Comment by adriankremer** [comment]
the used lodash version has a  "moderate" vulnerability -> https://snyk.io/vuln/npm:lodash

**Comment by janbiasi** [comment]
@adriankremer how about a PR 😺 would be great!

**Comment by ernscht** [comment]
22ee31a & f4a4e11

**Comment by ernscht** [comment]
published as [v2.0.2](https://www.npmjs.com/package/scss-config-webpack-plugin/v/2.0.2)
